### ISSUE TITLE
Use just one icon for save pop-up

### ISSUE THREAD

**Issue by dmigo** [dmigo/mood-tracker#7]

**Comment by dmigo** [comment]
## Floppy Disk Save Icon - Version B (Deep Cut Angular)

After exploring several variations, here's the final CSS implementation for the save icon:

### CSS Code
```css
.floppy-icon {
  position: relative;
  width: 60px;
  height: 60px;
  background: #000000;
  cursor: pointer;
  transition: all 0.1s ease;
  clip-path: polygon(0% 0%, 70% 0%, 100% 30%, 100% 100%, 0% 100%);
}

.floppy-icon:hover {
  transform: scale(1.05);
}

.top-label {
  position: absolute;
  top: 8px;
  left: 8px;
  right: 18px;
  height: 12px;
  background: #ffffff;
}

.write-protect-tab {
  position: absolute;
  top: 0;
  right: 0;
  width: 6px;
  height: 12px;
  background: #000000;
}

.main-label {
  position: absolute;
  bottom: 8px;
  left: 8px;
  right: 8px;
  height: 28px;
  background: #ffffff;
}
```

### HTML Structure
```html
<div class="floppy-icon">
  <div class="top-label">
    <div class="write-protect-tab"></div>
  </div>
  <div class="main-label"></div>
</div>
```

### Features
- Deep angular corner cut for distinctive floppy disk silhouette
- Clean black and white design
- Responsive hover effect
- Perfect for "Saving mood..." popups
- Matches neo-brutalist design aesthetic
