### ISSUE TITLE
🎨 History Page Redesign - Neo-Brutalist Scrollable Chart

### ISSUE THREAD

**Issue by dmigo** [dmigo/mood-tracker#9]
# 🎨 History Page Redesign - Neo-Brutalist Scrollable Chart

## Overview
Complete redesign of the history page to implement a scrollable 7-day mood chart with neo-brutalist styling, replacing the current timeline view.

### 📊 Chart Layout
- **Default View**: Last 7-8 days visible in viewport
- **Scrolling**: Horizontal scroll to navigate back in time
- **Data Points**: Weather emojis positioned at their mood level
- **Connection Line**: SVG path connecting mood points
- **Grid**: Chunky black grid lines for reference

#### Chart Container
```css
.chart-container {
  background: white;
  border: 4px solid #000000;
  box-shadow: 8px 8px 0px #000000;
  padding: 25px;
  margin: 20px;
}
```

#### Grid System
```css
.chart-grid {
  background-image: 
    linear-gradient(to right, #000000 3px, transparent 3px),
    linear-gradient(to bottom, #000000 3px, transparent 3px);
  background-size: 85.7px 60px; /* 7 days / 5 mood levels */
}
```

#### Mood Data Points
```css
.mood-point {
  width: 40px;
  height: 40px;
  border: 3px solid #000000;
  border-radius: 50%;
  box-shadow: 3px 3px 0px #000000;
  font-size: 20px; /* Weather emoji */
  cursor: pointer;
  transition: all 0.1s ease;
}

.mood-point:hover {
  transform: translate(-2px, -2px);
  box-shadow: 5px 5px 0px #000000;
}

.mood-point:active {
  transform: translate(1px, 1px);
  box-shadow: 2px 2px 0px #000000;
}
```

#### Y-Axis (Mood Levels)
- **Position**: Left side, outside chart area
- **Labels**: Weather emojis in bordered boxes
- **Levels**: ⛈️ 🌧️ ⛅ 🌤️ ☀️ (bottom to top)
```css
.y-label {
  font-size: 24px;
  background: white;
  border: 2px solid #000000;
  padding: 5px;
  box-shadow: 2px 2px 0px #000000;
}
```

#### X-Axis (Dates)
- **Format**: "Jun 16", "Jun 17", "Today"
- **Style**: Uppercase, bordered labels
```css
.x-label {
  font-weight: 900;
  text-transform: uppercase;
  letter-spacing: 1px;
  font-size: 12px;
  background: white;
  border: 2px solid #000000;
  padding: 5px 8px;
  box-shadow: 2px 2px 0px #000000;
}
```

#### Today Indicator
```css
.today-indicator {
  position: absolute;
  right: 45px;
  top: 0;
  bottom: 0;
  width: 3px;
  background: #ff0000;
  z-index: 10;
}
```

#### Connection Line
- **Implementation**: SVG path element
- **Style**: 3px black stroke with rounded caps
- **Path**: Connects all mood points chronologically

#### Scroll Behavior
- **Direction**: Horizontal only
- **Momentum**: Smooth scrolling with CSS `scroll-behavior: smooth`
- **Boundaries**: Snap to day boundaries
- **Infinite**: Scroll back to first mood entry

### 🎨 Color Palette Integration
Use existing mood colors for data point backgrounds:
```css
:root {
  --mood-1: #4a90a4; /* ⛈️ Very down */
  --mood-2: #6ba3b5; /* 🌧️ Somewhat down */
  --mood-3: #5ba05b; /* ⛅ Neutral */
  --mood-4: #f6dc5a; /* 🌤️ Pretty good */
  --mood-5: #f4d03f; /* ☀️ Very good */
}
```

### 📱 Mobile Responsiveness
- **Touch Scrolling**: Native momentum scrolling
- **Zoom**: Pinch to zoom for more/fewer days
- **Gestures**: Swipe left/right for navigation
- **Size**: Minimum 280px width for mobile

### 🔄 Navigation Integration
- **Header**: Keep existing "Today/History" toggle
- **Arrows**: Chunky neo-brutalist navigation buttons
```css
.nav-arrow {
  width: 60px;
  height: 60px;
  border: 4px solid #000000;
  background: var(--mood-3);
  border-radius: 50%;
  box-shadow: 4px 4px 0px #000000;
}
```

### 📊 Data Display
- **Click Interaction**: Tap any mood point to see details (date, mood level, notes, tags)
- **Tooltip**: Neo-brutalist popup with mood details
- **Empty Days**: Show as gaps or neutral indicators
- **Loading**: Brutalist loading spinner while fetching data

### 💾 Implementation Notes
- **Chart Width**: Dynamic based on data (85.7px per day)
- **Viewport**: 7-8 days visible (600px default width)
- **Performance**: Virtualize for large datasets (>100 days)
- **Accessibility**: Keyboard navigation, screen reader support

### 🎯 User Experience
1. **Default**: Show last 7 days on page load
2. **Scroll Left**: See historical mood data
3. **Today Line**: Always visible as reference point
4. **Smooth Transitions**: All interactions feel responsive
5. **Data Density**: Balance between detail and overview

### 🚀 Technical Requirements
- **Framework**: Vanilla JavaScript (maintain current approach)
- **Storage**: Use existing localStorage structure
- **PWA**: Maintain offline functionality
- **Performance**: 60fps scrolling, optimized rendering

### 📋 Acceptance Criteria
- [ ] 7-day scrollable chart with weather emoji data points
- [ ] Neo-brutalist styling (thick borders, chunky shadows)
- [ ] Smooth horizontal scrolling with momentum
- [ ] Interactive mood points with hover/click effects
- [ ] Today indicator line
- [ ] Responsive design for mobile
- [ ] Integration with existing mood data structure
- [ ] Maintains PWA offline functionality

---

**Priority**: High  
**Type**: Feature Enhancement  
**Estimated Effort**: 2-3 days  
**Dependencies**: Existing mood data structure, color palette (#7)
